version: '3'
services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - kafka-network

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - .env
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${MACHINE_IP}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
    networks:
      - kafka-network

  cmak:
    image: hlebalbau/kafka-manager:latest
    container_name: cmak
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zoo1:2181"  # Connect CMAK to Zookeeper
      CMAK_ARGS: "-Dconfig.file=/cmak/conf/application.conf -Dcmak.zkhosts=zoo1:2181 -Dcmak.kafka-manager.base-zk-paths=/kafka -Dcmak.clusters.0.name=local-cluster -Dcmak.clusters.0.zkhosts=zoo1:2181 -Dcmak.clusters.0.kafka-version=2.8.0 -Dcmak.clusters.0.jmx-enabled=true"
    depends_on:
      - kafka1
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
